<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Country;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountries($page)
    {
        $query = $this->createQueryBuilder('c')
            ->orderBy('c.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Country::NB_COUNTRIES_PER_PAGE)
            ->setMaxResults(Country::NB_COUNTRIES_PER_PAGE);

        return new Paginator($query);
    }
}
