<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Ratecategory;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RatecategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatecategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRatecategories($page)
    {
        $query = $this->createQueryBuilder('rc')
            ->orderBy('rc.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Ratecategory::NB_RATECATEGORIES_PER_PAGE)
            ->setMaxResults(Ratecategory::NB_RATECATEGORIES_PER_PAGE);

        return new Paginator($query);
    }
}
