<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Ratecode;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RatecodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatecodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRatecodes($page)
    {
        $query = $this->createQueryBuilder('rc')
            ->orderBy('rc.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Ratecode::NB_RATECODES_PER_PAGE)
            ->setMaxResults(Ratecode::NB_RATECODES_PER_PAGE);

        return new Paginator($query);
    }
}
