<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Reservationstatus;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ReservationstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationstatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReservationstatusWithHotel($page)
    {
        $query = $this->createQueryBuilder('rs')
            ->leftJoin('rs.hotel', 'h')
            ->addSelect('h')
            ->orderBy('rs.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Reservationstatus::NB_RESERVATIONSTATUS_PER_PAGE)
            ->setMaxResults(Reservationstatus::NB_RESERVATIONSTATUS_PER_PAGE);

        return new Paginator($query);
    }
}
