<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Roomtype;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RoomtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomtypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRoomtypesWithHotel($page)
    {
        $query = $this->createQueryBuilder('rt')
            ->leftJoin('rt.hotel', 'h')
            ->addSelect('h')
            ->orderBy('rt.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Roomtype::NB_ROOMTYPES_PER_PAGE)
            ->setMaxResults(Roomtype::NB_ROOMTYPES_PER_PAGE);

        return new Paginator($query);
    }
}
