<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Source;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSources($page)
    {
        $query = $this->createQueryBuilder('s')
            ->orderBy('s.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Source::NB_SOURCES_PER_PAGE)
            ->setMaxResults(Source::NB_SOURCES_PER_PAGE);

        return new Paginator($query);
    }
}
