<?php

namespace Datamart\MappingsBundle\Repository;
use Datamart\MappingsBundle\Entity\Travelagent;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TravelagentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelagentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTravelagents($page)
    {
        $query = $this->createQueryBuilder('ta')
            ->orderBy('ta.id')
            ->getQuery();

        $query->setFirstResult(($page-1)*Travelagent::NB_TRAVELAGENTS_PER_PAGE)
            ->setMaxResults(Travelagent::NB_TRAVELAGENTS_PER_PAGE);

        return new Paginator($query);
    }
}
